name: Deploy to EC2

on:
  push:
    branches:
      - main   # change if needed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy repo to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./"
          target: "/home/${{ secrets.EC2_USER }}/happy"

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/happy
            git reset --hard
            git pull origin main
            npm install
            npm rebuild bcrypt --build-from-source
            npx prisma generate
            pm2 restart server.js
            pm2 delete happy-backend || true
            AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }} \
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            AWS_REGION=ap-south-1 \
            pm2 start server.js --name happy-backend
