name: Deploy Happy Backend to EC2

on:
  push:
    branches:
      - main   # Trigger on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to target directory (create if not exists)
            mkdir -p /home/ec2-user/happy-backend
            cd /home/ec2-user/happy-backend

            # If repo already exists, pull latest, else clone
            if [ -d ".git" ]; then
              git reset --hard
              git pull origin main
            else
              git clone -b main https://github.com/chaaviesol/happy-backend.git .
            fi

            # Install dependencies
            npm install --production

            # Restart backend (using PM2, change if needed)
            pm2 restart happy-backend || pm2 start server.js --name happy-backend
